空值和缺失值的处理

In [2]:
import pandas as pd
from numpy import NaN
data_obj=pd.Series([1,None,NaN])
data_obj

0    1.0
1    NaN
2    NaN
dtype: float64

In [3]:
# isnull检查一下是否有空值或缺失值
pd.isnull(data_obj)

0    False
1     True
2     True
dtype: bool

In [4]:
#notnull 检查一下是否不为空值或缺失值
pd.notnull(data_obj)

0     True
1    False
2    False
dtype: bool

In [6]:
import pandas as pd
import numpy as np
df_obj = pd.DataFrame({"类别":['小说','散文随笔','青春文学','传记'],
                       "书名":[np.nan,'《皮囊》','《旅程结束时》','《老舍自传》'],
                       "作者":["老舍",None,"张启鑫","老舍"]})
df_obj

     类别       书名    作者
0    小说      NaN    老舍
1  散文随笔     《皮囊》  None
2  青春文学  《旅程结束时》   张启鑫
3    传记   《老舍自传》    老舍

In [7]:
#删除数据集中空值和缺失值
df_obj.dropna()

     类别       书名   作者
2  青春文学  《旅程结束时》  张启鑫
3    传记   《老舍自传》   老舍

In [8]:
#使用fillna进行填充
df_obj = pd.DataFrame({'A':[1,2,3,NaN],
                       'B':[NaN,4,NaN,6],
                       'C':['a',7,8,9],
                       'D':[NaN,2,3,NaN]})
df_obj

     A    B  C    D
0  1.0  NaN  a  NaN
1  2.0  4.0  7  2.0
2  3.0  NaN  8  3.0
3  NaN  6.0  9  NaN

In [9]:
df_obj.fillna("66.0")#使用的是66.0进行数据替换缺失值

      A     B  C     D
0   1.0  66.0  a  66.0
1   2.0   4.0  7   2.0
2   3.0  66.0  8   3.0
3  66.0   6.0  9  66.0

In [10]:
#对单个数据进行填充
df_obj.fillna({'A':4.0,'B':5.0})

     A    B  C    D
0  1.0  5.0  a  NaN
1  2.0  4.0  7  2.0
2  3.0  5.0  8  3.0
3  4.0  6.0  9  NaN

In [12]:
#重复值的处理
person_info = pd.DataFrame({'id':[1,2,3,4,4,5],
                            'name':['小铭','小月月','彭岩','刘华','刘华','周华'],
                            'age':[18,18,29,58,58,36],
                            'height':[180,180,185,175,175,178],
                            'gender':['女','女','男','男','男','男']})
person_info

   id name  age  height gender
0   1   小铭   18     180      女
1   2  小月月   18     180      女
2   3   彭岩   29     185      男
3   4   刘华   58     175      男
4   4   刘华   58     175      男
5   5   周华   36     178      男

In [13]:
#我像判断数据里面是不是有重复值
person_info.duplicated()

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool

In [14]:
#把重复值进行删除
person_info.drop_duplicates()

   id name  age  height gender
0   1   小铭   18     180      女
1   2  小月月   18     180      女
2   3   彭岩   29     185      男
3   4   刘华   58     175      男
5   5   周华   36     178      男

In [15]:
person_info

   id name  age  height gender
0   1   小铭   18     180      女
1   2  小月月   18     180      女
2   3   彭岩   29     185      男
3   4   刘华   58     175      男
4   4   刘华   58     175      男
5   5   周华   36     178      男

In [17]:
person_info.drop_duplicates(inplace=True)

In [18]:
person_info

   id name  age  height gender
0   1   小铭   18     180      女
1   2  小月月   18     180      女
2   3   彭岩   29     185      男
3   4   刘华   58     175      男
5   5   周华   36     178      男

In [19]:
#异常值的处理
df =pd.DataFrame({'菜谱名':['红烧肉','铁板鱿鱼',
                   '小炒肉','干锅鸭掌','酸菜鱼'],
                  '价格':[38,25,26,388,35]})
df

    菜谱名   价格
0   红烧肉   38
1  铁板鱿鱼   25
2   小炒肉   26
3  干锅鸭掌  388
4   酸菜鱼   35

In [20]:
df.replace(to_replace=388,value=38.8)

    菜谱名    价格
0   红烧肉  38.0
1  铁板鱿鱼  25.0
2   小炒肉  26.0
3  干锅鸭掌  38.8
4   酸菜鱼  35.0

更改数据类型

In [22]:
df = pd.DataFrame({'A':['8.1','9.0','4.2'],
                   'B':['-9','70','88'],
                   'C':['x','5.0','0']})
df

     A   B    C
0  8.1  -9    x
1  9.0  70  5.0
2  4.2  88    0

In [23]:
#这个方法是我们查看数据类型方法
df.dtypes

A    object
B    object
C    object
dtype: object

In [24]:
s=df['A'].astype(dtype='float')
s

0    8.1
1    9.0
2    4.2
Name: A, dtype: float64

In [25]:
s.astype(dtype='int')

0    8
1    9
2    4
Name: A, dtype: int32

In [26]:
df["B"].astype(dtype='int')

0    -9
1    70
2    88
Name: B, dtype: int32

In [27]:
ser_obj = pd.Series(['1','1.2','4.2'])
ser_obj

0      1
1    1.2
2    4.2
dtype: object

In [28]:
pd.to_numeric(ser_obj,errors='raise')

0    1.0
1    1.2
2    4.2
dtype: float64

In [29]:
#数据合并
import pandas as pd
df1 = pd.DataFrame({'A':['A0','A0','A1'],
                    'B':['B0','B0','B1'],
                    'C':['C0','C0','C1']})
df1

    A   B   C
0  A0  B0  C0
1  A0  B0  C0
2  A1  B1  C1

In [30]:
df2 = pd.DataFrame({'B':['B0','B0','B1'],
                    'C':['C0','C0','C1'],
                    'D':['D0','D2','D2']})
df2

    B   C   D
0  B0  C0  D0
1  B0  C0  D2
2  B1  C1  D2

In [35]:
#数据合并
#outer 是外连接 并集
#inner 是内连接 交际
pd.concat([df1,df2],join='outer',axis=1)

    A   B   C   B   C   D
0  A0  B0  C0  B0  C0  D0
1  A0  B0  C0  B0  C0  D2
2  A1  B1  C1  B1  C1  D2

In [33]:
pd.concat([df1,df2],join='inner',axis=0)

    B   C
0  B0  C0
1  B0  C0
2  B1  C1
0  B0  C0
1  B0  C0
2  B1  C1

重命名轴索引

In [38]:
df = pd.DataFrame({'A':['A0','A1','A2','A3'],
                   'B':['B0','B1','B2','B3'],
                   'C':['C0','C1','C2','C3']})
df

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3

In [39]:
df.rename(columns={'A':'a','B':'b','C':'c'},inplace=True)

In [40]:
df

    a   b   c
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3

数据的应用

In [43]:
data_frame = pd.DataFrame({'data1':[80,23,25,63,94,92,99,92,82,99],
                           'data2':[41,87,58,68,72,89,60,42,53,65],
                           'data3':[30,78,23,66,16,59,20,23,24,40],
                           'key':list('baabbabaaa')})
data_frame

   data1  data2  data3 key
0     80     41     30   b
1     23     87     78   a
2     25     58     23   a
3     63     68     66   b
4     94     72     16   b
5     92     89     59   a
6     99     60     20   b
7     92     42     23   a
8     82     53     24   a
9     99     65     40   a

In [46]:
#groupby 方法进行分组
data = data_frame.groupby("key")
for x in data:
    print(x)

('a',    data1  data2  data3 key
1     23     87     78   a
2     25     58     23   a
5     92     89     59   a
7     92     42     23   a
8     82     53     24   a
9     99     65     40   a)
('b',    data1  data2  data3 key
0     80     41     30   b
3     63     68     66   b
4     94     72     16   b
6     99     60     20   b)

In [50]:
dict([x for x in data])["a"]

   data1  data2  data3 key
1     23     87     78   a
2     25     58     23   a
5     92     89     59   a
7     92     42     23   a
8     82     53     24   a
9     99     65     40   a

In [51]:
dict([x for x in data])["b"]

   data1  data2  data3 key
0     80     41     30   b
3     63     68     66   b
4     94     72     16   b
6     99     60     20   b

In [52]:
data.apply(lambda x:x.sum()-x.min())

     data1  data2  data3
key
a      390    352    224
b      273    200    116

Pandas中的时间序列

In [58]:
import pandas as pd
import numpy as np
from datetime import datetime

In [59]:
dt=pd.to_datetime("2026-01-08")
dt

Timestamp('2026-01-08 00:00:00')

In [60]:
dt=pd.to_datetime("20260108")
dt

Timestamp('2026-01-08 00:00:00')

In [61]:
dt=pd.to_datetime("08/01/2026")
dt

Timestamp('2026-08-01 00:00:00')

In [62]:
date_list=['2015.6.1','2016.4.1',
           '2017.6.1','2018.1.23']
date_list

['2015.6.1', '2016.4.1', '2017.6.1', '2018.1.23']

In [63]:
date_index=pd.to_datetime(date_list)

In [65]:
date_se = pd.Series(np.arange(4),index=date_index)

In [66]:
date_se

2015-06-01    0
2016-04-01    1
2017-06-01    2
2018-01-23    3
dtype: int32

时间序列的生成

In [69]:
#开始的时间 结束时间
date=pd.date_range('2026/01/01','2026/08/20')
date

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05', '2026-01-06', '2026-01-07', '2026-01-08',
               '2026-01-09', '2026-01-10',
               ...
               '2026-08-11', '2026-08-12', '2026-08-13', '2026-08-14',
               '2026-08-15', '2026-08-16', '2026-08-17', '2026-08-18',
               '2026-08-19', '2026-08-20'],
              dtype='datetime64[ns]', length=232, freq='D')

In [70]:
date_index=pd.date_range('2026/01/08',periods=7)

In [71]:
date_index

DatetimeIndex(['2026-01-08', '2026-01-09', '2026-01-10', '2026-01-11',
               '2026-01-12', '2026-01-13', '2026-01-14'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
pd.date_range(start='2026/8/1 12:13:30',periods=5,
              tz='Asia/Hong_Kong')