安装

In [ ]:
! pip install pyecharts

In [16]:
# 一次性导入所有图例
from pyecharts.charts import * 
# 导入配置环境代码 可视化的依赖
from pyecharts.globals import CurrentConfig, NotebookType
CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_LAB
#配置选项
from pyecharts import options as opts
#主题的类型
from pyecharts.globals import ThemeType

In [17]:
bar = (
    #主题
    Bar(init_opts=opts.InitOpts(theme='white'))
    .add_xaxis(["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"])
    .add_yaxis("商家A",[5,20,36,10,75,90])
    .add_yaxis("商家B",[15,6,45,20,35,66])
    .set_global_opts(title_opts=opts.TitleOpts(title="今天要好好学习",subtitle="副标题"))
)
bar.load_javascript()

In [18]:
bar.render_notebook()

画布大小

In [19]:
#虚假数据
y=[198,45,23,22,22,19,13,13,10,10,10]
x=['羽绒服','裤子','保暖内衣','短外套','毛呢外套','皮草','女士包袋','棉衣/棉服','毛针织衫','羊毛衫']

#画布大小配置
bar = (
    Bar(init_opts=opts.InitOpts(width='600px',height='400px'))
    .add_xaxis(x)
    .add_yaxis('',y)
)
bar.load_javascript()
bar.render_notebook()

背景颜色

In [20]:
#虚假数据
x_data=['Apple','Huawei','Xiaomi','Oppo','Vivo','Meizu']
y_data_1 = [123,153,89,107,98,23]
y_data_2 = [231,321,135,341,245,167]

#画布大小
bar = (
    Bar(init_opts=opts.InitOpts(bg_color='rgba(255,182,193,0.4)'))
    .add_xaxis(x_data)
    .add_yaxis('',y_data_1)
    .add_yaxis('',y_data_2)
)
bar.load_javascript()
bar.render_notebook()

标题的位置

In [21]:
bar = (
    #主题
    Bar()
    .add_xaxis(["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"])
    .add_yaxis("商家",[5,20,36,10,75,90])
    .add_yaxis("商家",[15,6,45,20,35,66])
    .set_global_opts(title_opts=opts.TitleOpts(title="今天要好好学习",subtitle="副标题",pos_left='center',pos_top="10%"))
)
bar.load_javascript()
bar.render_notebook()

触发设置

In [22]:
#虚假数据
x_data = ['Apple','Huawei','Xiaomi','Oppo','Vivo','Meizu']
y_data_1 = [123,153,89,107,98,23]
y_data_2 = [231,321,135,341,245,167]
#提示框配置
bar =(
    Bar()
    .add_xaxis(x_data)
    .add_yaxis('图例1',y_data_1)
    .add_yaxis('图例2',y_data_2)
    .set_global_opts(tooltip_opts=opts.TooltipOpts(is_show=True,
                                                   #鼠标的移动或者点击时触发
                                                   trigger_on="mousemove|click"
                                                  ))
)
bar.load_javascript()
bar.render_notebook()

缩放比例

In [23]:
# 虚假数据
import random
x_data = list(range(1990,2020))
y_data_1 = [random.randint(0,100) for _ in x_data]
y_data_2 = [random.randint(0,100) for _ in x_data]
bar = (
    Bar()
    .add_xaxis(x_data)
    .add_yaxis('图例1',y_data_1)
    .add_yaxis('图例2',y_data_2)
    #缩放比例
    .set_global_opts(datazoom_opts=opts.DataZoomOpts(orient="vertical"))
)
bar.load_javascript()
bar.render_notebook()

page顺序多图

In [24]:
#虚假数据
x_data = ['Apple','Huawei','Xiaomi','Oppo','Vivo','Meizu']
y_data = [123,153,89,107,98,23]
bar = (Bar()
       .add_xaxis(x_data)
       .add_yaxis('',y_data)
      )
line = (Line()
        .add_xaxis(x_data)
        .add_yaxis('',y_data)
       )
page=Page()
page.add(bar,line)
page.load_javascript()
page.render("demo.html")

'D:\\编程教程\\Python-projects\\data-analysis\\demo.html'

In [25]:
# 虚假数据
x_data = ['Apple', 'Huawei', 'Xiaomi', 'Oppo', 'Vivo', 'Meizu']
y_data = [123, 153, 89, 107, 98, 23]
bar = (Bar()
       .add_xaxis(x_data)
       .add_yaxis('', y_data)
       )
line = (Line()
        .add_xaxis(x_data)
        .add_yaxis('', y_data)
        )
grid = (Grid()
        .add(bar,grid_opts=opts.GridOpts(pos_bottom="70%",pos_left="50%"))
        .add(line,grid_opts=opts.GridOpts(pos_left="15%"))
       )
grid.render_notebook()

In [31]:
#示例数据
import datetime
begin = datetime.date(2025, 4, 1)
end = datetime.date(2025, 4, 20)
cate=['Apple','Huawei','MI','Oppo','Vivo','Samsung']
#随机生成数据的方法
def random_data(n): return [random.randint(100,200) for i in range(n)]

#新建一个timeline对象
tl = Timeline()
tl.add_schema()

for i in range((end - begin).days + 1):
    day = begin + datetime.timedelta(days=i)

    bar = (Bar()
           .add_xaxis(cate)
           .add_yaxis('电商渠道',random_data(len(cate)))
          )
    tl.add(bar,day)

tl.render_notebook()

In [35]:
#选项卡
cate = ['Apple','Huawei','MI','Oppo','Vivo','Samsung']

#时间范围
begin = datetime.date(2026,4,1)
end = datetime.date(2026,4,20)
date_list = [str(begin + datetime.timedelta(days=i))
             for i in range((end - begin).days + 1)]

#随机生成数据的方法
def random_data(n): return [random.randint(100,200) for i in range(n)]

#新建一个tab对象
tab= Tab()

for c in cate:
    day = begin + datetime.timedelta(days=i)

    line =(Line()
           .add_xaxis(date_list)
           .add_yaxis('',random_data(len(date_list)))
          )
    tab.add(line,c)

tab.render_notebook()

In [40]:
import pandas as pd
data=pd.read_excel(r"D:\编程教程\Python-projects\data-analysis\抖音近期商品热门商品排行.xlsx")
data.head()

,商品名称,商品价格,所属店铺,商品类别,商品类目,商品种类,商品销量,关联直播,关联达人,关联视频
0,时尚羽绒服女中长款冬季连帽保暖外套3085,2799.0,来自小店,羽绒服,女装,服饰鞋帽,7176,1,1,0
1,BB【御寒天下】老钱系Fleece Jackets 飞行员羊毛夹克外套BB2747,1826.0,NaN,夹克,男装,服饰鞋帽,7194,0,0,0
2,【杉杉】男女同款远红外发热休闲舒适净版打底衫PY08,599.0,来自小店,针织衫/毛衣,男装,服饰鞋帽,12006,0,0,0
3,3S鲨鱼裤组合装【张柏芝同款】MissWiss秋冬鲨鱼裤高腰休闲裤,279.0,来自小店,裤子,女装,服饰鞋帽,24033,5,3,0
4,BB【荣耀王者】老钱系Fleece Jackets 专业版羊毛外套BB2729,1530.0,NaN,夹克,男装,服饰鞋帽,3689,0,0,0

In [42]:
data.describe()

              商品价格          商品销量        关联直播        关联达人        关联视频
count   500.000000    500.000000  500.000000  500.000000  500.000000
mean    905.436880   4313.734000   20.070000   18.840000    3.346000
std    1407.618562   5405.915072   69.391812   62.112723   12.947492
min      14.800000     44.000000    0.000000    0.000000    0.000000
25%     136.725000    865.000000    1.000000    1.000000    0.000000
50%     399.000000   2008.500000    1.000000    1.000000    0.000000
75%     999.000000   6132.250000    4.000000    3.250000    2.000000
max    9900.000000  34751.000000  696.000000  578.000000  236.000000

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   商品名称    500 non-null    object
 1   商品价格    500 non-null    float64
 2   所属店铺    440 non-null    object
 3   商品类别    500 non-null    object
 4   商品类目    500 non-null    object
 5   商品种类    500 non-null    object
 6   商品销量    500 non-null    int64
 7   关联直播    500 non-null    int64
 8   关联达人    500 non-null    int64
 9   关联视频    500 non-null    int64
dtypes: float64(1), int64(4), object(5)
memory usage: 39.2+ KB

商品类别分析

In [44]:
data["商品类别"].unique()

array(['羽绒服', '夹克', '针织衫/毛衣', '裤子', '女士包袋', '派克服', '棉衣/棉服', '棉衣', '斜挎包',
       '设计师/潮牌女装', '毛呢外套', '短外套', '奢品箱包', '羊毛衫', '面部护肤', '中老年女装', '塑身衣',
       '保暖内衣', '内裤', '休闲裤', '面部彩妆', '卫裤', '靴子', '皮草', '袜子', '唇部彩妆', '低帮鞋',
       '外套/夹克/大衣', '巧克力', '眼部护理', '风衣', '面部美容仪器', 'T恤', '户外服装', '卫衣/绒衫',
       '美发电器', '睡衣', '毛衣', '牛仔裤', '毛针织衫', '染发烫发/头发造型', '取暖器', '腕表',
       '蔬菜/蔬菜制品', '手部护理', '羽绒服饰/羽绒内胆', '中国联通充值卡', '电子教育', '钱币', '篮球鞋',
       '破壁机', '女士内衣', '运动鞋', '洗发护发', '水果', '衬衫', '唐装/民族服装/舞台服装', '国产白酒',
       '卫衣', '半身裙', '羊绒衫', '套装/学生校服/工作制服', '马夹', '毛呢大衣', '随身WiFi',
       '挂饰/生肖挂饰', '海鲜水产及制品', '跑步鞋', '洗地机', '运动羽绒服', '防护用品', '皮衣'],
      dtype=object)

In [45]:
bar_list=data["商品类别"].value_counts().head(10)
bar_list

商品类别
羽绒服      198
裤子        48
保暖内衣      23
短外套       22
毛呢外套      19
皮草        13
女士包袋      13
棉衣/棉服     10
毛针织衫      10
羊毛衫       10
Name: count, dtype: int64

In [46]:
bar_list.index.tolist()

['羽绒服', '裤子', '保暖内衣', '短外套', '毛呢外套', '皮草', '女士包袋', '棉衣/棉服', '毛针织衫', '羊毛衫']

In [47]:
bar_list.values.tolist()

[198, 48, 23, 22, 19, 13, 13, 10, 10, 10]

In [53]:
y=[198,48,23,22,19,13,13,10,10,10]
x=['羽绒服','裤子','保暖内衣','短外套','毛呢外套','皮草','女士包袋','棉衣/棉服','毛针织衫','羊毛衫']

In [54]:
#画布大小配置
bar = (
    Bar()
    .add_xaxis(x)
    .add_yaxis('商品个数',y)
)
bar.load_javascript()

In [56]:
bar.render_notebook()

In [57]:
#商品价格
data["商品价格"]=data["商品价格"].astype(int)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   商品名称    500 non-null    object
 1   商品价格    500 non-null    int32
 2   所属店铺    440 non-null    object
 3   商品类别    500 non-null    object
 4   商品类目    500 non-null    object
 5   商品种类    500 non-null    object
 6   商品销量    500 non-null    int64
 7   关联直播    500 non-null    int64
 8   关联达人    500 non-null    int64
 9   关联视频    500 non-null    int64
dtypes: int32(1), int64(4), object(5)
memory usage: 37.2+ KB

In [58]:
data["price_cut"]=pd.cut(data["商品价格"],bins=[0,500,1000,1500,2000,3000,5000])
data.head(10)

,商品名称,商品价格,所属店铺,商品类别,商品类目,商品种类,商品销量,关联直播,关联达人,关联视频,price_cut
0,时尚羽绒服女中长款冬季连帽保暖外套3085,2799,来自小店,羽绒服,女装,服饰鞋帽,7176,1,1,0,"(2000, 3000]"
1,BB【御寒天下】老钱系Fleece Jackets 飞行员羊毛夹克外套BB2747,1826,NaN,夹克,男装,服饰鞋帽,7194,0,0,0,"(1500, 2000]"
2,【杉杉】男女同款远红外发热休闲舒适净版打底衫PY08,599,来自小店,针织衫/毛衣,男装,服饰鞋帽,12006,0,0,0,"(500, 1000]"
3,3S鲨鱼裤组合装【张柏芝同款】MissWiss秋冬鲨鱼裤高腰休闲裤,279,来自小店,裤子,女装,服饰鞋帽,24033,5,3,0,"(0, 500]"
4,BB【荣耀王者】老钱系Fleece Jackets 专业版羊毛外套BB2729,1530,NaN,夹克,男装,服饰鞋帽,3689,0,0,0,"(1500, 2000]"
5,GELANNI头层牛皮休闲百搭子母水桶包,1089,来自小店,女士包袋,箱包,礼品箱包,4507,0,0,0,"(1000, 1500]"
6,《冰魂雪魄》COCO姐男朋友人手一件的黑金加绒派克服,999,NaN,派克服,女装,服饰鞋帽,4848,0,0,0,"(500, 1000]"
7,【张予曦同款】G双件装她语6.0秋冬加绒加厚鲨鱼喇叭裤收腹提臀显瘦,229,来自小店,裤子,女装,服饰鞋帽,19542,2,1,0,"(0, 500]"
8,《凛冬将至》COCO姐男朋友们都在穿的火山岩极寒加绒加厚棉服,999,NaN,棉衣/棉服,女装,服饰鞋帽,4322,0,0,0,"(500, 1000]"
9,东大门连帽长款时尚百搭潮流韩版羽绒服D273,599,来自小店,羽绒服,女装,服饰鞋帽,7202,2,1,0,"(500, 1000]"

In [59]:
data.price_cut.cat.categories

IntervalIndex([(0, 500], (500, 1000], (1000, 1500], (1500, 2000], (2000, 3000],
               (3000, 5000]],
              dtype='interval[int64, right]')

In [62]:
data["price_qut"]=pd.qcut(data["商品价格"],6,labels=["实用","经济","小奢","中奢","大奢","老钱"])
data.head()

,商品名称,商品价格,所属店铺,商品类别,商品类目,商品种类,商品销量,关联直播,关联达人,关联视频,price_cut,price_qut
0,时尚羽绒服女中长款冬季连帽保暖外套3085,2799,来自小店,羽绒服,女装,服饰鞋帽,7176,1,1,0,"(2000, 3000]",老钱
1,BB【御寒天下】老钱系Fleece Jackets 飞行员羊毛夹克外套BB2747,1826,NaN,夹克,男装,服饰鞋帽,7194,0,0,0,"(1500, 2000]",老钱
2,【杉杉】男女同款远红外发热休闲舒适净版打底衫PY08,599,来自小店,针织衫/毛衣,男装,服饰鞋帽,12006,0,0,0,"(500, 1000]",中奢
3,3S鲨鱼裤组合装【张柏芝同款】MissWiss秋冬鲨鱼裤高腰休闲裤,279,来自小店,裤子,女装,服饰鞋帽,24033,5,3,0,"(0, 500]",小奢
4,BB【荣耀王者】老钱系Fleece Jackets 专业版羊毛外套BB2729,1530,NaN,夹克,男装,服饰鞋帽,3689,0,0,0,"(1500, 2000]",老钱

In [63]:
data["price_qut"].value_counts()

price_qut
小奢    97
实用    84
经济    83
老钱    83
大奢    81
中奢    72
Name: count, dtype: int64