Pandas的数据结构分析

In [1]:
import pandas as pd

In [2]:
ser_obj=pd.Series(data=[1,2,3,4,5])
ser_obj

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
#指定索引
ser_obj=pd.Series(data=[1,2,3,4,5],index=['a','b','c','d','e'])
ser_obj

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [4]:
#字典数据
info={"name":"zhangsan","title":"teacher"}
data=pd.Series(data=info)
data

name     zhangsan
title     teacher
dtype: object

In [5]:
data.index

Index(['name', 'title'], dtype='object')

In [6]:
data.values

array(['zhangsan', 'teacher'], dtype=object)

In [7]:
data+"ha"

name     zhangsanha
title     teacherha
dtype: object

In [8]:
#dataFrame 二维表格数据
import numpy as np
demo_arr=np.array([['a','b','c'],['d','e','f']])
demo_arr

array([['a', 'b', 'c'],
       ['d', 'e', 'f']], dtype='<U1')

In [9]:
df_obj=pd.DataFrame(demo_arr,columns=['NO1','NO2','NO3'])
df_obj

  NO1 NO2 NO3
0   a   b   c
1   d   e   f

In [10]:
# 获取的列索引为"No2"的一列数据？
e=df_obj['NO2']
e

0    b
1    e
Name: NO2, dtype: object

In [12]:
e=df_obj.NO2
e

0    b
1    e
Name: NO2, dtype: object

In [13]:
#添加一列数据
df_obj['NO4']=['h','h']

In [14]:
df_obj

  NO1 NO2 NO3 NO4
0   a   b   c   h
1   d   e   f   h

In [15]:
#删除一列数据
del df_obj['NO3']

In [16]:
df_obj

  NO1 NO2 NO4
0   a   b   h
1   d   e   h

In [21]:
df=pd.DataFrame(data=[[80,75,90],[68,96,85]],index=["小明","小户"],columns=["语文","数学","英语"])
df

    语文  数学  英语
小明  80  75  90
小户  68  96  85

In [22]:
df["数学"]

小明    75
小户    96
Name: 数学, dtype: int64

In [23]:
df['历史']=['90','88']

In [24]:
df

    语文  数学  英语  历史
小明  80  75  90  90
小户  68  96  85  88

In [25]:
#Pandas索引操作以及高级索引
ser_obj=pd.Series([1,2,3,4,5],index=['c','d','a','b','e'])
ser_obj

c    1
d    2
a    3
b    4
e    5
dtype: int64

In [26]:
#重新索引
ser_obj2=ser_obj.reindex(['a','b','c','d','e','f'])
ser_obj2

a    3.0
b    4.0
c    1.0
d    2.0
e    5.0
f    NaN
dtype: float64

In [27]:
ser_obj2=ser_obj.reindex(['a','b','d','e','f'],fill_value=6)
ser_obj2

a    3
b    4
d    2
e    5
f    6
dtype: int64

In [28]:
#DataFrame.reindex(index=None,colums=None,method=None,copy=True,Fill_value=nan,limit=None)
ser_obj3=pd.Series([1,3,5,7],index=[0,2,4,6])
ser_obj3

0    1
2    3
4    5
6    7
dtype: int64

In [29]:
ser_obj3.reindex(range(6),method='ffill')##重新索引，向前填充值

0    1
1    1
2    3
3    3
4    5
5    5
dtype: int64

In [30]:
for i in range(6):
    print(i)

0
1
2
3
4
5

In [31]:
ser_obj3.reindex(range(6),method='bfill')## #重新索引，向后填充值

0    1
1    3
2    3
3    5
4    5
5    7
dtype: int64

In [32]:
ser_obj = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
ser_obj

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [33]:
#我想获取3这个数据 可以通过位置 使用索引位置获取数据
ser_obj[2]

C:\Users\Administrator\AppData\Local\Temp\ipykernel_12760\632343238.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser_obj[2]

3

In [34]:
ser_obj['c']#使用索引名称获取数据

3

In [36]:
ser_obj[['c','d']]#使用索引名称进行切片

c    3
d    4
dtype: int64

In [37]:
ser_obj[2:4]##使用位置索引进行切片

c    3
d    4
dtype: int64

In [38]:
ser_obj =pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
ser_obj

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [39]:
#获取的不连续的数据
ser_obj[['a','c','e']]

a    1
c    3
e    5
dtype: int64

In [40]:
#获取的不连续的数据
ser_obj[[0,2,4]]

C:\Users\Administrator\AppData\Local\Temp\ipykernel_12760\2461488609.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser_obj[[0,2,4]]

a    1
c    3
e    5
dtype: int64

In [42]:
#布尔型同样适合用于Pandas
ser_bool=ser_obj>2
ser_bool

a    False
b    False
c     True
d     True
e     True
dtype: bool

In [43]:
ser_obj[ser_bool]

c    3
d    4
e    5
dtype: int64

In [44]:
#DataFrame的索引操作
arr = np.arange(12).reshape(3,4)
df_obj=pd.DataFrame(arr,columns=['a','b','c','d'])
df_obj

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [45]:
df_obj['b']

0    1
1    5
2    9
Name: b, dtype: int32

In [46]:
df_obj[['b','d']]

   b   d
0  1   3
1  5   7
2  9  11

In [50]:
df_obj[:2]

   a  b  c  d
0  0  1  2  3
1  4  5  6  7

In [51]:
#使用多个切片先通过索引获取第0~2行的数据，在通过不连续列索引获取第b，d列的数据
df_obj[:2][['b','d']]

   b  d
0  1  3
1  5  7

In [52]:
df_obj[:3][['b','d']]

   b   d
0  1   3
1  5   7
2  9  11

In [53]:
#算数运算与数据对齐
obj_one=pd.Series(range(10,13),index=range(3))
obj_one

0    10
1    11
2    12
dtype: int64

In [54]:
obj_two=pd.Series(range(20,25),index=range(5))
obj_two

0    20
1    21
2    22
3    23
4    24
dtype: int64

In [55]:
obj_one+obj_two

0    30.0
1    32.0
2    34.0
3     NaN
4     NaN
dtype: float64

In [56]:
#不想出现这种缺失值 add fill_value
obj_one.add(obj_two,fill_value=0)

0    30.0
1    32.0
2    34.0
3    23.0
4    24.0
dtype: float64

数据排序

In [58]:
ser_obj=pd.Series(range(10,15),index=[5,3,1,3,2])
ser_obj

5    10
3    11
1    12
3    13
2    14
dtype: int64

In [59]:
ser_obj.sort_index()

1    12
2    14
3    11
3    13
5    10
dtype: int64

In [60]:
ser_obj.sort_index(ascending=False)

5    10
3    11
3    13
2    14
1    12
dtype: int64

In [62]:
df_obj = pd.DataFrame(np.arange(9).reshape(3,3),index=[4,3,5])
df_obj

   0  1  2
4  0  1  2
3  3  4  5
5  6  7  8

In [63]:
df_obj.sort_index()

   0  1  2
3  3  4  5
4  0  1  2
5  6  7  8

In [64]:
df_obj.sort_index(ascending=False)

   0  1  2
5  6  7  8
4  0  1  2
3  3  4  5

In [65]:
ser_obj = pd.Series([4,np.nan,6,np.nan,-3,2])
ser_obj

0    4.0
1    NaN
2    6.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [66]:
#按值进行排序
ser_obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    6.0
1    NaN
3    NaN
dtype: float64

In [68]:
df_obj=pd.DataFrame([[0.4,-0.1,-0.3,0.0],
                     [0.2,0.6,-0.1,-0.7],
                     [0.8,0.6,-0.5,0.1]])
df_obj

     0    1    2    3
0  0.4 -0.1 -0.3  0.0
1  0.2  0.6 -0.1 -0.7
2  0.8  0.6 -0.5  0.1

In [69]:
df_obj.sort_values(by=2)

     0    1    2    3
2  0.8  0.6 -0.5  0.1
0  0.4 -0.1 -0.3  0.0
1  0.2  0.6 -0.1 -0.7

In [70]:
#读写数据操作
df=pd.DataFrame({'one_name':[1,2,3],'two_name':[4,5,6]})
df

   one_name  two_name
0         1         4
1         2         5
2         3         6

In [71]:
#我要把df对象写入到csv数据
df.to_csv('./itcast.csv',index=False)

In [72]:
#读取数据
file_data=pd.read_csv('./itcast.csv')
file_data

   one_name  two_name
0         1         4
1         2         5
2         3         6

读写excel文件

In [74]:
df1=pd.DataFrame({'col1':['云','缨'],'col2':['老','师']})
df1

  col1 col2
0    云    老
1    缨    师

In [75]:
df1.to_excel(r'./itcast.xlsx','pythonvip班')

C:\Users\Administrator\AppData\Local\Temp\ipykernel_12760\660920629.py:1: FutureWarning: Starting with pandas version 3.0 all arguments of to_excel except for the argument 'excel_writer' will be keyword-only.
  df1.to_excel(r'./itcast.xlsx','pythonvip班')

In [76]:
data=pd.read_excel(r'./itcast.xlsx',sheet_name=None)
data

{'pythonvip班':    Unnamed: 0 col1 col2
 0           0    云    老
 1           1    缨    师}

In [80]:
#读取html的表格数据
import requests
data=requests.get("https://www.dxsbb.com/news/126858.html")
data

In [82]:
html_data=pd.read_html(data.content,encoding='utf-8')
html_data

[     0         1    2
 0   排名        名称  所在地
 1    1      清华大学   北京
 2    2      北京大学   北京
 3    3  中国科学技术大学   安徽
 4    4      复旦大学   上海
 5    5    中国人民大学   北京
 6    6    上海交通大学   上海
 7    7      南京大学   江苏
 8    8      同济大学   上海
 9    9      浙江大学   浙江
 10  10      南开大学   天津
 11  11  北京航空航天大学   北京
 12  12    北京师范大学   北京
 13  13      武汉大学   湖北
 14  14    西安交通大学   陕西
 15  15      天津大学   天津
 16  16    华中科技大学   湖北
 17  17    北京理工大学   北京
 18  18      东南大学   江苏
 19  19      中山大学   广东
 20  20    华东师范大学   上海
 21  21   哈尔滨工业大学  黑龙江
 22  22      厦门大学   福建
 23  23    西北工业大学   陕西
 24  24      中南大学   湖南
 25  25    大连理工大学   辽宁
 26  26      四川大学   四川
 27  27    电子科技大学   四川
 28  28    华南理工大学   广东
 29  29      吉林大学   吉林
 30  30      湖南大学   湖南
 31  31      重庆大学   重庆
 32  32      山东大学   山东
 33  33    中国农业大学   北京
 34  34    中国海洋大学   山东
 35  35    中央民族大学   北京
 36  36      东北大学   辽宁
 37  37      兰州大学   甘肃
 38  38  西北农林科技大学   陕西
 39  暂无    国防科技大学   湖南,
       0         1    2
 0    排名        名称  所在地
 1     1      清华大学   北京
 2     2      北京大学   北京
 3     3  中国科学技术大学   安徽
 4     4      复旦大学   上海
 ..   ..       ...  ...
 111  暂无    国防科技大学   湖南
 112  暂无    中央音乐学院   北京
 113  暂无    第二军医大学   上海
 114  暂无    第四军医大学   陕西
 115  暂无      西藏大学   西藏

 [116 rows x 3 columns]]

In [83]:
html_data[1]

      0         1    2
0    排名        名称  所在地
1     1      清华大学   北京
2     2      北京大学   北京
3     3  中国科学技术大学   安徽
4     4      复旦大学   上海
..   ..       ...  ...
111  暂无    国防科技大学   湖南
112  暂无    中央音乐学院   北京
113  暂无    第二军医大学   上海
114  暂无    第四军医大学   陕西
115  暂无      西藏大学   西藏

[116 rows x 3 columns]

In [84]:
html_data[0]

     0         1    2
0   排名        名称  所在地
1    1      清华大学   北京
2    2      北京大学   北京
3    3  中国科学技术大学   安徽
4    4      复旦大学   上海
5    5    中国人民大学   北京
6    6    上海交通大学   上海
7    7      南京大学   江苏
8    8      同济大学   上海
9    9      浙江大学   浙江
10  10      南开大学   天津
11  11  北京航空航天大学   北京
12  12    北京师范大学   北京
13  13      武汉大学   湖北
14  14    西安交通大学   陕西
15  15      天津大学   天津
16  16    华中科技大学   湖北
17  17    北京理工大学   北京
18  18      东南大学   江苏
19  19      中山大学   广东
20  20    华东师范大学   上海
21  21   哈尔滨工业大学  黑龙江
22  22      厦门大学   福建
23  23    西北工业大学   陕西
24  24      中南大学   湖南
25  25    大连理工大学   辽宁
26  26      四川大学   四川
27  27    电子科技大学   四川
28  28    华南理工大学   广东
29  29      吉林大学   吉林
30  30      湖南大学   湖南
31  31      重庆大学   重庆
32  32      山东大学   山东
33  33    中国农业大学   北京
34  34    中国海洋大学   山东
35  35    中央民族大学   北京
36  36      东北大学   辽宁
37  37      兰州大学   甘肃
38  38  西北农林科技大学   陕西
39  暂无    国防科技大学   湖南